### PR TITLE
Add contribution guidelines

### PR DESCRIPTION
**Pull request by tfidfwastaken**
I have added contribution guidelines that, when followed will ensure
less BT for us and a clean commit history for everyone involved

By the simple rebase operations outlined, it will also help our
contributors feel confident in other real-world contribution scenarios
where the maintainer expects a clean set of commits in the commit
history of the PR

Please do check if this is not too bhaari to understand :p

### CODE REVIEW

**Comment by tfidfwastaken** [comment]
Oof, just as I pushed I remembered that github has an option for "squash and merge" in the arrow next to "merge pull request".

So now there is a tradeoff. Should I simplify the instruction where I mention squashing, so the PR can have be a littered mess and we deal with it and make their change into one commit using GitHub's "squash and merge"?

The latter will make it easier for contributors, but the former will teach them more, which can be useful when contributing to other projects

**Comment by MadhavJivrajani** [comment]
Since this project is starting to get attention from people who are not a part of PESOS, according to me, ease of contribution should be a priority, square and merge seems like the better option.

**Comment by tfidfwastaken** [comment]
Alright, I will remove the mention of squashes. I think our main priority should be accessibility.

**Comment by MadhavJivrajani** [comment]
Will wait for @Gituser143 and @metonymic-smokey 's opinion before confirming merge

**Comment by tfidfwastaken** [comment]
Okay I have made the instructions a little more simpler. Feel free to squash and merge these two commits when you are ready ;)

**Comment by MadhavJivrajani** [comment]
Yeah, I'll enable that

**Pull request merged**
