### PR TITLE
Add per proc export functionality. [WIP]

### PR DESCRIPTION
**Pull request by Gituser143**
# Description

Implemented per process JSON export functionality. This builds on #63 
Currently the JSON output is stored fully in memory, waiting on @MadhavJivrajani for help :P

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have read the [contribution guidelines](https://github.com/pesos/grofer/blob/master/CONTRIBUTING.md) and followed it as far as possible. 
- [x] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [x] I have run `go fmt` on my code ([reference](https://blog.golang.org/gofmt))
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings 
- [x] Any dependent and pending changes have been merged and published

### CODE REVIEW

**Comment by Gituser143** [comment]
@MadhavJivrajani do you think it would be a good idea to keep these export functions in a separate `export` package? I've currently put per proc exports as part of this new package.

**Comment by MadhavJivrajani** [comment]
This should be fun

**Comment by MadhavJivrajani** [comment]
> @MadhavJivrajani do you think it would be a good idea to keep these export functions in a separate export package? I've currently put per proc exports as part of this new package.

Why is is `package proc` for general export?

**Comment by Gituser143** [comment]
> Why is it package proc for general export?
Woops, little mess up, sorry!

**Comment by Gituser143** [comment]
@MadhavJivrajani  Also, how do you plan to write JSON data record by record?

**Comment by MadhavJivrajani** [comment]
#72

**Pull request closed without merging**
